name: CMake

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


# Use a bash shell so we can use the same syntax for environment variable
# access regardless of the host operating system
defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        include:
        - os: ubuntu-latest
          ENABLE_COVERAGE: ON

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r test/requirements.txt
    - name: Build Project
      uses: threeal/cmake-action@v2.0.0
      with:
        options: |
          CMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
          ENABLE_COVERAGE:BOOL=${{ matrix.ENABLE_COVERAGE }}
        bulld-args: |
          --config $BUILD_TYPE
    - name: Test Project
      uses: threeal/ctest-action@v1.1.0
      with:
         build-config: $BUILD_TYPE
    - name: Check Test Coverage
      uses: threeal/gcovr-action@v1.1.0
      with:
        html-out: coverage.html
        html-details: true
        html-title: Test Coverage Report
        html-theme: github.green
